// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: amitis/petalregistry/v1/query.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryPetalRequest is request type for the Query/Petal RPC method
type QueryPetalRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryPetalRequest) Reset()         { *m = QueryPetalRequest{} }
func (m *QueryPetalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPetalRequest) ProtoMessage()    {}
func (*QueryPetalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fef155a57122ccb, []int{0}
}
func (m *QueryPetalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPetalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPetalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPetalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPetalRequest.Merge(m, src)
}
func (m *QueryPetalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPetalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPetalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPetalRequest proto.InternalMessageInfo

func (m *QueryPetalRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryPetalResponse is response type for the Query/Petal RPC method
type QueryPetalResponse struct {
	Petal *Petal `protobuf:"bytes,1,opt,name=petal,proto3" json:"petal,omitempty"`
}

func (m *QueryPetalResponse) Reset()         { *m = QueryPetalResponse{} }
func (m *QueryPetalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPetalResponse) ProtoMessage()    {}
func (*QueryPetalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fef155a57122ccb, []int{1}
}
func (m *QueryPetalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPetalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPetalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPetalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPetalResponse.Merge(m, src)
}
func (m *QueryPetalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPetalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPetalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPetalResponse proto.InternalMessageInfo

func (m *QueryPetalResponse) GetPetal() *Petal {
	if m != nil {
		return m.Petal
	}
	return nil
}

// QueryPetalsRequest is request type for the Query/Petals RPC method
type QueryPetalsRequest struct {
}

func (m *QueryPetalsRequest) Reset()         { *m = QueryPetalsRequest{} }
func (m *QueryPetalsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPetalsRequest) ProtoMessage()    {}
func (*QueryPetalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fef155a57122ccb, []int{2}
}
func (m *QueryPetalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPetalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPetalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPetalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPetalsRequest.Merge(m, src)
}
func (m *QueryPetalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPetalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPetalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPetalsRequest proto.InternalMessageInfo

// QueryPetalsResponse is response type for the Query/Petals RPC method
type QueryPetalsResponse struct {
	Petals []*Petal `protobuf:"bytes,1,rep,name=petals,proto3" json:"petals,omitempty"`
}

func (m *QueryPetalsResponse) Reset()         { *m = QueryPetalsResponse{} }
func (m *QueryPetalsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPetalsResponse) ProtoMessage()    {}
func (*QueryPetalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fef155a57122ccb, []int{3}
}
func (m *QueryPetalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPetalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPetalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPetalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPetalsResponse.Merge(m, src)
}
func (m *QueryPetalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPetalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPetalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPetalsResponse proto.InternalMessageInfo

func (m *QueryPetalsResponse) GetPetals() []*Petal {
	if m != nil {
		return m.Petals
	}
	return nil
}

// QueryPetalsByOwnerRequest is request type for the Query/PetalsByOwner RPC method
type QueryPetalsByOwnerRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryPetalsByOwnerRequest) Reset()         { *m = QueryPetalsByOwnerRequest{} }
func (m *QueryPetalsByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPetalsByOwnerRequest) ProtoMessage()    {}
func (*QueryPetalsByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fef155a57122ccb, []int{4}
}
func (m *QueryPetalsByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPetalsByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPetalsByOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPetalsByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPetalsByOwnerRequest.Merge(m, src)
}
func (m *QueryPetalsByOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPetalsByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPetalsByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPetalsByOwnerRequest proto.InternalMessageInfo

func (m *QueryPetalsByOwnerRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

// QueryPetalsByOwnerResponse is response type for the Query/PetalsByOwner RPC method
type QueryPetalsByOwnerResponse struct {
	Petals []*Petal `protobuf:"bytes,1,rep,name=petals,proto3" json:"petals,omitempty"`
}

func (m *QueryPetalsByOwnerResponse) Reset()         { *m = QueryPetalsByOwnerResponse{} }
func (m *QueryPetalsByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPetalsByOwnerResponse) ProtoMessage()    {}
func (*QueryPetalsByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fef155a57122ccb, []int{5}
}
func (m *QueryPetalsByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPetalsByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPetalsByOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPetalsByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPetalsByOwnerResponse.Merge(m, src)
}
func (m *QueryPetalsByOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPetalsByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPetalsByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPetalsByOwnerResponse proto.InternalMessageInfo

func (m *QueryPetalsByOwnerResponse) GetPetals() []*Petal {
	if m != nil {
		return m.Petals
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryPetalRequest)(nil), "amitis.petalregistry.v1.QueryPetalRequest")
	proto.RegisterType((*QueryPetalResponse)(nil), "amitis.petalregistry.v1.QueryPetalResponse")
	proto.RegisterType((*QueryPetalsRequest)(nil), "amitis.petalregistry.v1.QueryPetalsRequest")
	proto.RegisterType((*QueryPetalsResponse)(nil), "amitis.petalregistry.v1.QueryPetalsResponse")
	proto.RegisterType((*QueryPetalsByOwnerRequest)(nil), "amitis.petalregistry.v1.QueryPetalsByOwnerRequest")
	proto.RegisterType((*QueryPetalsByOwnerResponse)(nil), "amitis.petalregistry.v1.QueryPetalsByOwnerResponse")
}

func init() {
	proto.RegisterFile("amitis/petalregistry/v1/query.proto", fileDescriptor_2fef155a57122ccb)
}

var fileDescriptor_2fef155a57122ccb = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0xcc, 0xcd, 0x2c,
	0xc9, 0x2c, 0xd6, 0x2f, 0x48, 0x2d, 0x49, 0xcc, 0x29, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x29, 0xaa,
	0xd4, 0x2f, 0x33, 0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x87, 0x28, 0xd2, 0x43, 0x51, 0xa4, 0x57, 0x66, 0x28, 0x25, 0x93, 0x9e, 0x9f, 0x9f, 0x9e,
	0x93, 0xaa, 0x9f, 0x58, 0x90, 0xa9, 0x9f, 0x98, 0x97, 0x97, 0x5f, 0x92, 0x58, 0x92, 0x99, 0x9f,
	0x57, 0x0c, 0xd1, 0x26, 0x85, 0xd3, 0x6c, 0xb0, 0x00, 0x44, 0x91, 0x92, 0x32, 0x97, 0x60, 0x20,
	0xc8, 0xaa, 0x00, 0x90, 0x58, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x10, 0x1f, 0x17, 0x53,
	0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x53, 0x66, 0x8a, 0x92, 0x17, 0x97, 0x10,
	0xb2, 0xa2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x13, 0x2e, 0x56, 0xb0, 0x49, 0x60, 0x85,
	0xdc, 0x46, 0x72, 0x7a, 0x38, 0x9c, 0xa9, 0x07, 0xd1, 0x06, 0x51, 0xac, 0x24, 0x82, 0x6c, 0x56,
	0x31, 0xd4, 0x46, 0x25, 0x5f, 0x2e, 0x61, 0x14, 0x51, 0xa8, 0x15, 0x66, 0x5c, 0x6c, 0x60, 0x5d,
	0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x44, 0xd8, 0x01, 0x55, 0xad, 0x64, 0xc8, 0x25, 0x89, 0x64, 0x9c,
	0x53, 0xa5, 0x7f, 0x79, 0x5e, 0x6a, 0x11, 0xcc, 0x77, 0x22, 0x5c, 0xac, 0xf9, 0x20, 0x3e, 0xd8,
	0xdd, 0x9c, 0x41, 0x10, 0x8e, 0x52, 0x08, 0x97, 0x14, 0x36, 0x2d, 0x94, 0x39, 0xc4, 0xe8, 0x06,
	0x33, 0x17, 0x2b, 0xd8, 0x58, 0xa1, 0x5e, 0x46, 0x2e, 0x56, 0xb0, 0x9c, 0x90, 0x16, 0x4e, 0xbd,
	0x18, 0x31, 0x21, 0xa5, 0x4d, 0x94, 0x5a, 0x88, 0x23, 0x95, 0xb4, 0x9b, 0x2e, 0x3f, 0x99, 0xcc,
	0xa4, 0x2a, 0xa4, 0xac, 0x8f, 0x37, 0xe6, 0xf5, 0xab, 0x33, 0x53, 0x6a, 0x85, 0x7a, 0x18, 0xb9,
	0xd8, 0x20, 0x7e, 0x15, 0x22, 0xc6, 0x12, 0x58, 0x4c, 0x49, 0xe9, 0x10, 0xa7, 0x18, 0xea, 0x24,
	0x75, 0xb0, 0x93, 0x14, 0x85, 0xe4, 0xf1, 0x3b, 0xa9, 0x58, 0x68, 0x3d, 0x23, 0x17, 0x2f, 0x4a,
	0xd0, 0x0b, 0x19, 0x11, 0x63, 0x11, 0x6a, 0xd4, 0x4a, 0x19, 0x93, 0xa4, 0x07, 0xea, 0x46, 0x53,
	0xb0, 0x1b, 0xf5, 0x85, 0x74, 0x09, 0xb8, 0x51, 0x1f, 0x9c, 0x50, 0xf4, 0xab, 0xc1, 0x54, 0xad,
	0x53, 0xc4, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1,
	0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0xd9, 0xa5, 0x67, 0x96,
	0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0x42, 0x8d, 0xd4, 0xcd, 0x4b, 0x2d, 0x29, 0xcf, 0x2f,
	0xca, 0x46, 0xe7, 0x56, 0xa0, 0xd9, 0x55, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0xce, 0x9a,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0x06, 0x21, 0x2a, 0x1d, 0x04, 0x00, 0x00,
}

func (m *QueryPetalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPetalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPetalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPetalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPetalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPetalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Petal != nil {
		{
			size, err := m.Petal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPetalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPetalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPetalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPetalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPetalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPetalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Petals) > 0 {
		for iNdEx := len(m.Petals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Petals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryPetalsByOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPetalsByOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPetalsByOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPetalsByOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPetalsByOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPetalsByOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Petals) > 0 {
		for iNdEx := len(m.Petals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Petals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPetalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryPetalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Petal != nil {
		l = m.Petal.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPetalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPetalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Petals) > 0 {
		for _, e := range m.Petals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryPetalsByOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPetalsByOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Petals) > 0 {
		for _, e := range m.Petals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPetalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPetalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPetalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPetalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPetalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPetalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Petal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Petal == nil {
				m.Petal = &Petal{}
			}
			if err := m.Petal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPetalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPetalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPetalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPetalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPetalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPetalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Petals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Petals = append(m.Petals, &Petal{})
			if err := m.Petals[len(m.Petals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPetalsByOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPetalsByOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPetalsByOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPetalsByOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPetalsByOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPetalsByOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Petals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Petals = append(m.Petals, &Petal{})
			if err := m.Petals[len(m.Petals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
