// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: amitis/petalregistry/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Petal_FullMethodName         = "/amitis.petalregistry.v1.Query/Petal"
	Query_Petals_FullMethodName        = "/amitis.petalregistry.v1.Query/Petals"
	Query_PetalsByOwner_FullMethodName = "/amitis.petalregistry.v1.Query/PetalsByOwner"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service
type QueryClient interface {
	// Petal queries a petal by ID
	Petal(ctx context.Context, in *QueryPetalRequest, opts ...grpc.CallOption) (*QueryPetalResponse, error)
	// Petals queries all petals
	Petals(ctx context.Context, in *QueryPetalsRequest, opts ...grpc.CallOption) (*QueryPetalsResponse, error)
	// PetalsByOwner queries petals owned by an address
	PetalsByOwner(ctx context.Context, in *QueryPetalsByOwnerRequest, opts ...grpc.CallOption) (*QueryPetalsByOwnerResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Petal(ctx context.Context, in *QueryPetalRequest, opts ...grpc.CallOption) (*QueryPetalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPetalResponse)
	err := c.cc.Invoke(ctx, Query_Petal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Petals(ctx context.Context, in *QueryPetalsRequest, opts ...grpc.CallOption) (*QueryPetalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPetalsResponse)
	err := c.cc.Invoke(ctx, Query_Petals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PetalsByOwner(ctx context.Context, in *QueryPetalsByOwnerRequest, opts ...grpc.CallOption) (*QueryPetalsByOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPetalsByOwnerResponse)
	err := c.cc.Invoke(ctx, Query_PetalsByOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service
type QueryServer interface {
	// Petal queries a petal by ID
	Petal(context.Context, *QueryPetalRequest) (*QueryPetalResponse, error)
	// Petals queries all petals
	Petals(context.Context, *QueryPetalsRequest) (*QueryPetalsResponse, error)
	// PetalsByOwner queries petals owned by an address
	PetalsByOwner(context.Context, *QueryPetalsByOwnerRequest) (*QueryPetalsByOwnerResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Petal(context.Context, *QueryPetalRequest) (*QueryPetalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Petal not implemented")
}
func (UnimplementedQueryServer) Petals(context.Context, *QueryPetalsRequest) (*QueryPetalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Petals not implemented")
}
func (UnimplementedQueryServer) PetalsByOwner(context.Context, *QueryPetalsByOwnerRequest) (*QueryPetalsByOwnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PetalsByOwner not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Petal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPetalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Petal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Petal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Petal(ctx, req.(*QueryPetalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Petals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPetalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Petals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Petals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Petals(ctx, req.(*QueryPetalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PetalsByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPetalsByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PetalsByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PetalsByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PetalsByOwner(ctx, req.(*QueryPetalsByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amitis.petalregistry.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Petal",
			Handler:    _Query_Petal_Handler,
		},
		{
			MethodName: "Petals",
			Handler:    _Query_Petals_Handler,
		},
		{
			MethodName: "PetalsByOwner",
			Handler:    _Query_PetalsByOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "amitis/petalregistry/v1/query.proto",
}
