// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: amitis/petalregistry/v1/tx.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdatePetalMetadata updates a petal's metadata
type MsgUpdatePetalMetadata struct {
	Owner       string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	PetalId     uint64 `protobuf:"varint,2,opt,name=petal_id,json=petalId,proto3" json:"petal_id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *MsgUpdatePetalMetadata) Reset()         { *m = MsgUpdatePetalMetadata{} }
func (m *MsgUpdatePetalMetadata) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePetalMetadata) ProtoMessage()    {}
func (*MsgUpdatePetalMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_1873efd36e78fc65, []int{0}
}
func (m *MsgUpdatePetalMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePetalMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePetalMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePetalMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePetalMetadata.Merge(m, src)
}
func (m *MsgUpdatePetalMetadata) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePetalMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePetalMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePetalMetadata proto.InternalMessageInfo

func (m *MsgUpdatePetalMetadata) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgUpdatePetalMetadata) GetPetalId() uint64 {
	if m != nil {
		return m.PetalId
	}
	return 0
}

func (m *MsgUpdatePetalMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgUpdatePetalMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// MsgUpdatePetalMetadataResponse defines the response
type MsgUpdatePetalMetadataResponse struct {
}

func (m *MsgUpdatePetalMetadataResponse) Reset()         { *m = MsgUpdatePetalMetadataResponse{} }
func (m *MsgUpdatePetalMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePetalMetadataResponse) ProtoMessage()    {}
func (*MsgUpdatePetalMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1873efd36e78fc65, []int{1}
}
func (m *MsgUpdatePetalMetadataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePetalMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePetalMetadataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePetalMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePetalMetadataResponse.Merge(m, src)
}
func (m *MsgUpdatePetalMetadataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePetalMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePetalMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePetalMetadataResponse proto.InternalMessageInfo

// MsgTransferPetal transfers ownership of a petal to a new address
type MsgTransferPetal struct {
	Owner    string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	PetalId  uint64 `protobuf:"varint,2,opt,name=petal_id,json=petalId,proto3" json:"petal_id,omitempty"`
	NewOwner string `protobuf:"bytes,3,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty"`
}

func (m *MsgTransferPetal) Reset()         { *m = MsgTransferPetal{} }
func (m *MsgTransferPetal) String() string { return proto.CompactTextString(m) }
func (*MsgTransferPetal) ProtoMessage()    {}
func (*MsgTransferPetal) Descriptor() ([]byte, []int) {
	return fileDescriptor_1873efd36e78fc65, []int{2}
}
func (m *MsgTransferPetal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferPetal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferPetal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferPetal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferPetal.Merge(m, src)
}
func (m *MsgTransferPetal) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferPetal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferPetal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferPetal proto.InternalMessageInfo

func (m *MsgTransferPetal) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgTransferPetal) GetPetalId() uint64 {
	if m != nil {
		return m.PetalId
	}
	return 0
}

func (m *MsgTransferPetal) GetNewOwner() string {
	if m != nil {
		return m.NewOwner
	}
	return ""
}

// MsgTransferPetalResponse defines the response
type MsgTransferPetalResponse struct {
	PetalId  uint64 `protobuf:"varint,1,opt,name=petal_id,json=petalId,proto3" json:"petal_id,omitempty"`
	NewOwner string `protobuf:"bytes,2,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty"`
}

func (m *MsgTransferPetalResponse) Reset()         { *m = MsgTransferPetalResponse{} }
func (m *MsgTransferPetalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferPetalResponse) ProtoMessage()    {}
func (*MsgTransferPetalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1873efd36e78fc65, []int{3}
}
func (m *MsgTransferPetalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferPetalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferPetalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferPetalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferPetalResponse.Merge(m, src)
}
func (m *MsgTransferPetalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferPetalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferPetalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferPetalResponse proto.InternalMessageInfo

func (m *MsgTransferPetalResponse) GetPetalId() uint64 {
	if m != nil {
		return m.PetalId
	}
	return 0
}

func (m *MsgTransferPetalResponse) GetNewOwner() string {
	if m != nil {
		return m.NewOwner
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgUpdatePetalMetadata)(nil), "amitis.petalregistry.v1.MsgUpdatePetalMetadata")
	proto.RegisterType((*MsgUpdatePetalMetadataResponse)(nil), "amitis.petalregistry.v1.MsgUpdatePetalMetadataResponse")
	proto.RegisterType((*MsgTransferPetal)(nil), "amitis.petalregistry.v1.MsgTransferPetal")
	proto.RegisterType((*MsgTransferPetalResponse)(nil), "amitis.petalregistry.v1.MsgTransferPetalResponse")
}

func init() { proto.RegisterFile("amitis/petalregistry/v1/tx.proto", fileDescriptor_1873efd36e78fc65) }

var fileDescriptor_1873efd36e78fc65 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xbf, 0x4f, 0xe3, 0x30,
	0x18, 0xad, 0xfb, 0xe3, 0xae, 0xf5, 0xe9, 0xa4, 0x53, 0xae, 0xba, 0xe6, 0x72, 0x52, 0x14, 0x75,
	0xea, 0x55, 0xba, 0x44, 0x3d, 0x06, 0x24, 0x06, 0x06, 0x36, 0x86, 0x08, 0x14, 0x81, 0x84, 0x58,
	0x2a, 0xb7, 0x31, 0x26, 0xa2, 0xb1, 0x23, 0xdb, 0x34, 0xed, 0x04, 0x62, 0x65, 0xe1, 0x4f, 0xe9,
	0x9f, 0xc1, 0xd8, 0x91, 0x11, 0xb5, 0x43, 0xff, 0x09, 0x06, 0x14, 0x5b, 0x45, 0xa4, 0x2a, 0x15,
	0xdd, 0xbe, 0xf7, 0xe5, 0xbd, 0xf7, 0xbd, 0x7c, 0xb6, 0xa1, 0x83, 0xe2, 0x48, 0x46, 0xc2, 0x4b,
	0xb0, 0x44, 0x03, 0x8e, 0x49, 0x24, 0x24, 0x1f, 0x7b, 0xc3, 0x8e, 0x27, 0x47, 0x6e, 0xc2, 0x99,
	0x64, 0x46, 0x43, 0x33, 0xdc, 0x1c, 0xc3, 0x1d, 0x76, 0xac, 0x46, 0x9f, 0x89, 0x98, 0x09, 0x2f,
	0x16, 0x24, 0x13, 0xc4, 0x82, 0x68, 0x85, 0x55, 0x27, 0x8c, 0x30, 0x55, 0x7a, 0x59, 0xa5, 0xbb,
	0xcd, 0x7b, 0x00, 0x7f, 0xf9, 0x82, 0x9c, 0x26, 0x21, 0x92, 0xf8, 0x38, 0x33, 0xf3, 0xb1, 0x44,
	0x21, 0x92, 0xc8, 0xa8, 0xc3, 0x0a, 0x4b, 0x29, 0xe6, 0x26, 0x70, 0x40, 0xab, 0x16, 0x68, 0x60,
	0xfc, 0x86, 0x55, 0x35, 0xb3, 0x1b, 0x85, 0x66, 0xd1, 0x01, 0xad, 0x72, 0xf0, 0x55, 0xe1, 0xc3,
	0xd0, 0x30, 0x60, 0x99, 0xa2, 0x18, 0x9b, 0x25, 0xc5, 0x57, 0xb5, 0xe1, 0xc0, 0x6f, 0x21, 0x16,
	0x7d, 0x1e, 0x25, 0x32, 0x62, 0xd4, 0x2c, 0xab, 0x4f, 0xef, 0x5b, 0x7b, 0xf0, 0x6e, 0x31, 0x69,
	0x6b, 0xf3, 0xa6, 0x03, 0xed, 0xf5, 0x61, 0x02, 0x2c, 0x12, 0x46, 0x05, 0x6e, 0x0e, 0xe0, 0x0f,
	0x5f, 0x90, 0x13, 0x8e, 0xa8, 0xb8, 0xc0, 0x5c, 0x71, 0xb6, 0x0f, 0xfa, 0x07, 0xd6, 0x28, 0x4e,
	0xbb, 0x5a, 0xa4, 0xd3, 0x56, 0x29, 0x4e, 0x8f, 0x32, 0x9c, 0xcb, 0x13, 0x40, 0x73, 0x75, 0xda,
	0x32, 0x49, 0xce, 0x1f, 0x6c, 0xf0, 0x2f, 0xe6, 0xfd, 0xff, 0xbf, 0x00, 0x58, 0xf2, 0x05, 0x31,
	0x6e, 0xe0, 0xcf, 0x75, 0x5b, 0xf7, 0xdc, 0x0f, 0x4e, 0xd6, 0x5d, 0xbf, 0x19, 0x6b, 0x77, 0x4b,
	0xc1, 0xdb, 0x0f, 0xc4, 0xf0, 0x7b, 0x7e, 0x8f, 0x7f, 0x37, 0x39, 0xe5, 0xa8, 0x56, 0xe7, 0xd3,
	0xd4, 0xe5, 0x38, 0xab, 0x72, 0xbb, 0x98, 0xb4, 0xc1, 0xc1, 0xd9, 0xe3, 0xcc, 0x06, 0xd3, 0x99,
	0x0d, 0x9e, 0x67, 0x36, 0x78, 0x98, 0xdb, 0x85, 0xe9, 0xdc, 0x2e, 0x3c, 0xcd, 0xed, 0xc2, 0xf9,
	0x3e, 0x89, 0xe4, 0xe5, 0x75, 0xcf, 0xed, 0xb3, 0xd8, 0xd3, 0xee, 0xff, 0x28, 0x96, 0x29, 0xe3,
	0x57, 0xab, 0x70, 0xb4, 0xf2, 0x30, 0xe4, 0x38, 0xc1, 0xa2, 0xf7, 0x45, 0xdd, 0xe8, 0x9d, 0xd7,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x6d, 0xfd, 0x57, 0x3d, 0x03, 0x00, 0x00,
}

func (m *MsgUpdatePetalMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePetalMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePetalMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PetalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PetalId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePetalMetadataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePetalMetadataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePetalMetadataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferPetal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferPetal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferPetal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewOwner) > 0 {
		i -= len(m.NewOwner)
		copy(dAtA[i:], m.NewOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewOwner)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PetalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PetalId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferPetalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferPetalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferPetalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewOwner) > 0 {
		i -= len(m.NewOwner)
		copy(dAtA[i:], m.NewOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewOwner)))
		i--
		dAtA[i] = 0x12
	}
	if m.PetalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PetalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdatePetalMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PetalId != 0 {
		n += 1 + sovTx(uint64(m.PetalId))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdatePetalMetadataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferPetal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PetalId != 0 {
		n += 1 + sovTx(uint64(m.PetalId))
	}
	l = len(m.NewOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgTransferPetalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PetalId != 0 {
		n += 1 + sovTx(uint64(m.PetalId))
	}
	l = len(m.NewOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdatePetalMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePetalMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePetalMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PetalId", wireType)
			}
			m.PetalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PetalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePetalMetadataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePetalMetadataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePetalMetadataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferPetal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferPetal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferPetal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PetalId", wireType)
			}
			m.PetalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PetalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferPetalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferPetalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferPetalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PetalId", wireType)
			}
			m.PetalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PetalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
