// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: amitis/petalregistry/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_UpdatePetalMetadata_FullMethodName = "/amitis.petalregistry.v1.Msg/UpdatePetalMetadata"
	Msg_TransferPetal_FullMethodName       = "/amitis.petalregistry.v1.Msg/TransferPetal"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the petalregistry Msg service
type MsgClient interface {
	// UpdatePetalMetadata allows the owner to update petal name/description
	UpdatePetalMetadata(ctx context.Context, in *MsgUpdatePetalMetadata, opts ...grpc.CallOption) (*MsgUpdatePetalMetadataResponse, error)
	// TransferPetal transfers ownership of a petal to a new address
	TransferPetal(ctx context.Context, in *MsgTransferPetal, opts ...grpc.CallOption) (*MsgTransferPetalResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdatePetalMetadata(ctx context.Context, in *MsgUpdatePetalMetadata, opts ...grpc.CallOption) (*MsgUpdatePetalMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdatePetalMetadataResponse)
	err := c.cc.Invoke(ctx, Msg_UpdatePetalMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferPetal(ctx context.Context, in *MsgTransferPetal, opts ...grpc.CallOption) (*MsgTransferPetalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgTransferPetalResponse)
	err := c.cc.Invoke(ctx, Msg_TransferPetal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the petalregistry Msg service
type MsgServer interface {
	// UpdatePetalMetadata allows the owner to update petal name/description
	UpdatePetalMetadata(context.Context, *MsgUpdatePetalMetadata) (*MsgUpdatePetalMetadataResponse, error)
	// TransferPetal transfers ownership of a petal to a new address
	TransferPetal(context.Context, *MsgTransferPetal) (*MsgTransferPetalResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) UpdatePetalMetadata(context.Context, *MsgUpdatePetalMetadata) (*MsgUpdatePetalMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePetalMetadata not implemented")
}
func (UnimplementedMsgServer) TransferPetal(context.Context, *MsgTransferPetal) (*MsgTransferPetalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferPetal not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdatePetalMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePetalMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePetalMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdatePetalMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePetalMetadata(ctx, req.(*MsgUpdatePetalMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferPetal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferPetal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferPetal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_TransferPetal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferPetal(ctx, req.(*MsgTransferPetal))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amitis.petalregistry.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePetalMetadata",
			Handler:    _Msg_UpdatePetalMetadata_Handler,
		},
		{
			MethodName: "TransferPetal",
			Handler:    _Msg_TransferPetal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "amitis/petalregistry/v1/tx.proto",
}
